### ISSUE TITLE
Trying to save file gives "Error: No device specified for platform iphonesimulator..."

### ISSUE THREAD

**Issue by mxl** [kballard/vim-swift#2]
```
Error: No device specified for platform iphonesimulator
Please set b:swift_device or g:swift_device and try again
```

Could you please add some documentation about plugin options?

**Comment by lilyball** [comment]
Oh sorry, I bet this is because you have Syntastic installed and are saving a file with `import UIKit` in it? I didn't think about the fact that you'd get a surprising warning like that.  I'll fix it. It really shouldn't actually need a device selected just to compile (all it uses the device for at that stage is to decide whether to compile for `i386` or `x86_64`), so I'll make it assume a reasonable default. The device selection is really meant for running scripts with ⌘R.

**Comment by lilyball** [comment]
Running `:help ft-swift` will give documentation on the plugin, but I should probably add documentation to the README as well.

**Comment by mxl** [comment]
@kballard Yes. Now it works. Thanks!
